// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjhiLihlWPxwQw4TfB-MG7vPqVW_KsHMU',
    appId: '1:43082183993:web:da5de380f3d56579d864e8',
    messagingSenderId: '43082183993',
    projectId: 'spacenews-core-ff039',
    authDomain: 'spacenews-core-ff039.firebaseapp.com',
    storageBucket: 'spacenews-core-ff039.firebasestorage.app',
    measurementId: 'G-8MLB7ZKEX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ7g73TQJQ8_twzDxlAmCrDufJtyCYQa4',
    appId: '1:43082183993:android:77520a33c84e4a6cd864e8',
    messagingSenderId: '43082183993',
    projectId: 'spacenews-core-ff039',
    storageBucket: 'spacenews-core-ff039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4oZEBcgefFTEWwvgSDDFEBG2pI3spMVU',
    appId: '1:43082183993:ios:5a41fadd46d497f5d864e8',
    messagingSenderId: '43082183993',
    projectId: 'spacenews-core-ff039',
    storageBucket: 'spacenews-core-ff039.firebasestorage.app',
    iosBundleId: 'com.example.remed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4oZEBcgefFTEWwvgSDDFEBG2pI3spMVU',
    appId: '1:43082183993:ios:5a41fadd46d497f5d864e8',
    messagingSenderId: '43082183993',
    projectId: 'spacenews-core-ff039',
    storageBucket: 'spacenews-core-ff039.firebasestorage.app',
    iosBundleId: 'com.example.remed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjhiLihlWPxwQw4TfB-MG7vPqVW_KsHMU',
    appId: '1:43082183993:web:10259ed173ae42e4d864e8',
    messagingSenderId: '43082183993',
    projectId: 'spacenews-core-ff039',
    authDomain: 'spacenews-core-ff039.firebaseapp.com',
    storageBucket: 'spacenews-core-ff039.firebasestorage.app',
    measurementId: 'G-YQE9D1MW04',
  );
}
